name: n2o sample

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: ['20.3', '21.3', '22.2']
        rebar3: ['3.14.1', '3.14.3']

    steps:
        - uses: actions/checkout@v3
        - uses: erlef/setup-beam@v1
          with:
            otp-version: ${{matrix.otp}}
            rebar3-version: ${{matrix.rebar3}}
        - run: rebar3 get-deps
        - run: rebar3 shell
